app/users/forms.py
import re

from flask_wtf import FlaskForm
from wtforms import PasswordField, BooleanField, SubmitField, StringField
from wtforms.fields.html5 import EmailField
from wtforms.validators import DataRequired, Email, EqualTo, ValidationError

from app.models import User


class LoginForm(FlaskForm):
    email = EmailField('Почта', validators=[DataRequired()])
    password = PasswordField('Пароль', validators=[DataRequired()])
    remember_me = BooleanField('Запомнить меня')
    submit = SubmitField('Войти')

    def validate(self):
        if not super().validate():
            return False
        user = User.query.filter_by(email=self.email.data).first()
        if user is None:
            self.email.errors.append('Пользователя с такой почтой не существует')
            return False
        if not user.check_password(self.password.data):
            self.password.errors.append('Неверный пароль')
            return False
        return True


class RegistrationForm(FlaskForm):
    name = StringField('Никнейм', validators=[DataRequired()])
    email = StringField('Почта', validators=[DataRequired(), Email()])
    password = PasswordField('Пароль', validators=[DataRequired()])
    password2 = PasswordField(
        'Повторите пароль', validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Зарегистрироваться')

    def validate_name(self, name):
        user = User.query.filter_by(name=name.data).first()
        if user is not None:
            raise ValidationError('Данный никнейм уже занят')
        if name.data.isdigit():
            raise ValidationError("Имя не может состоять только из цифр")
        if not re.fullmatch(r"[a-zA-Z1-9_]*", name.data):
            raise ValidationError("Имя может содержать лишь латинские буквы,"
                                  " цифры и символы подчеркивания")

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user is not None:
            raise ValidationError('Данная почта уже занята')

app/users/blueprint.py
import json
from datetime import datetime
from functools import wraps

import requests
from flask import Blueprint, redirect, render_template, url_for, flash, jsonify, request, session
from flask_breadcrumbs import register_breadcrumb, default_breadcrumb_root
from flask_login import current_user, login_user, login_required, logout_user, LoginManager
from oauthlib.oauth2 import InvalidGrantError
from requests_oauthlib import OAuth2Session

from .forms import LoginForm, RegistrationForm
from app.app import db, app
from app.email import send_email, send_email_async
from app.models import User, Session
from app.token import generate_confirmation_token, confirm_token
from ..constants import FINISHED

login_manager = LoginManager()
login_manager.init_app(app)

users = Blueprint("users", __name__, template_folder="templates")
default_breadcrumb_root(users, '.')


def check_confirmed(func):
    @wraps(func)
    def decorated_function(*args, **kwargs):
        if current_user.confirmed is False:
            flash('Пожалуйста, подтвердите свой аккаунт', 'warning')
            return redirect(url_for('users.unconfirmed'))
        return func(*args, **kwargs)

    return decorated_function


@login_manager.user_loader
def load_user(user_id):
    return db.session.query(User).get(user_id)


@login_manager.unauthorized_handler
def catch():
    return redirect(
        url_for("users.login", next=request.url if request.url != url_for("users.logout") else ""))


@users.errorhandler(404)
def error404(e):
    return render_template("users/404.html"), 404


@users.route('/login', methods=['GET', 'POST'])
@register_breadcrumb(users, '.login', 'Авторизация')
def login():
    if current_user.is_authenticated:
        return redirect(url_for("home"))
    form = LoginForm()
    if form.validate_on_submit():
        user = db.session.query(User).filter(User.email == form.email.data).first()
        login_user(user, remember=form.remember_me.data)
        return redirect(request.args.get("next", "/"))
    return render_template('users/login.html', title='Авторизация', form=form)


@users.route('/registration', methods=['GET', 'POST'])
@register_breadcrumb(users, '.registration', 'Регистрация')
def registration():
    if current_user.is_authenticated:
        return redirect(url_for("home"))
    form = RegistrationForm()
    if form.validate_on_submit():
        try:
            user = User(name=form.name.data, email=form.email.data, password=form.password.data,
                        confirmed=False)
            db.session.add(user)
            db.session.commit()
        except Exception as e:
            print(e)
        token = generate_confirmation_token(user.email)
        confirm_url = url_for('users.confirm_email', token=token, _external=True)
        html = render_template('users/activate.html', confirm_url=confirm_url)
        subject = "Пожалуйста, подтвердите свою почту"
        login_user(user)
        send_email_async(user.email, subject, html)
        flash('Письмо для подтверждения было отправленно', 'success')
        return redirect(url_for("users.unconfirmed"))
    return render_template('users/registration.html', title='Регистрация', form=form)


@users.route('/confirm/<token>')
@register_breadcrumb(users, '.confirmation', 'Подтверждение почты')
def confirm_email(token):
    try:
        email = confirm_token(token)
    except:
        flash('Ссылка для подтверждения больше не работает.', 'danger')
    user = User.query.filter_by(email=email).first_or_404()
    if user.confirmed:
        flash('Аккаунт уже подтвержден. Пожалуйста, авторизуйтесь.', 'success')
    else:
        user.confirmed = True
        user.confirmed_on = datetime.now()
        db.session.commit()
        flash('Вы подтвердили аккаунт. Спасибо!', 'success')
    return redirect("/")


@users.route('/unconfirmed')
@login_required
@register_breadcrumb(users, '.unconfirmed', 'Профиль')
def unconfirmed():
    if current_user.confirmed:
        return redirect("/")
    flash('Пожалуйста, подтвердите аккаунт!', 'warning')
    return render_template('users/unconfirmed.html')


@users.route('/resend')
@login_required
@register_breadcrumb(users, '.resend', 'Профиль')
def resend_confirmation():
    token = generate_confirmation_token(current_user.email)
    confirm_url = url_for('users.confirm_email', token=token, _external=True)
    html = render_template('users/activate.html', confirm_url=confirm_url)
    subject = "Пожалуйста, подтвердите ваш электронный адресс"
    send_email(current_user.email, subject, html)
    flash('Новое письмо для подтверждения отправленно', 'success')
    return redirect(url_for('users.unconfirmed'))


@users.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect("/")


def profile_breadcrumbs(*args, **kwargs):
    name = request.view_args.get('name')
    if not name:
        return [{'text': 'Профиль', 'url': url_for("users.profile")}]
    user = User.query.filter(User.name == name).first()
    if not user:
        return [{'text': 'Профиль', 'url': url_for("users.profile")}, {'text': "Ошибка", 'url': ""}]
    return [{'text': 'Профиль', 'url': url_for("users.profile")},
            {'text': user.name, 'url': url_for("users.profile", name=user.name)}]


@users.route("/profile")
@users.route("/profile/<name>")
@login_required
@check_confirmed
@register_breadcrumb(users, '.profile', '', dynamic_list_constructor=profile_breadcrumbs)
def profile(name=""):
    page = request.args.get("page")
    if page and page.isdigit():
        page = int(page)
    else:
        page = 1
    if name and name != current_user.name:
        user = User.query.filter(User.name == name).first_or_404()
        sessions = user.sessions.filter(Session.status == FINISHED).paginate(page=page, per_page=10)
        return render_template("users/profile.html", title="Профиль: " + name,
                               user=user, sessions=sessions)
    try:
        if current_user.token_info:
            discord_s = make_session(token=json.loads(current_user.token_info))
            user = discord_s.get(app.config["API_BASE_URL"] + '/users/@me').json()
            if user.get('message') and user["message"] == "401: Unauthorized":
                user = {}
                session["oauth2_token"] = None
        else:
            user = {}
    except InvalidGrantError:
        current_user.token_info = None
        user = {}

    sessions = current_user.sessions.filter(Session.status == FINISHED).paginate(page=page,
                                                                                 per_page=10)
    return render_template("users/profile.html", title="Профиль", user=current_user,
                           discord_user=user, sessions=sessions)


friends = Blueprint("friends", __name__, template_folder="templates")


@friends.route("/", methods=["GET"])
@login_required
def get_friends():
    response = {"confirmed": [], "received": [], "requested": []}
    for f in current_user.friends:
        friend = {"name": f.name, "status": f.in_client, "session": {}}
        if f.sessions:
            friend["session"]["id"] = f.sessions[0].id
            friend["session"]["status"] = f.sessions[0].status
            friend["session"]["name"] = f.sessions[0].name
        response["confirmed"].append(friend)
    for f in current_user.followers:
        friend = {"name": f.name, "status": f.in_client, "session": {}}
        if f.sessions:
            friend["session"]["id"] = f.sessions[0].id
            friend["session"]["status"] = f.sessions[0].status
            friend["session"]["name"] = f.sessions[0].name
        response["received"].append(friend)
    for f in current_user.follows:
        friend = {"name": f.name, "status": f.in_client, "session": {}}
        if f.sessions:
            friend["session"]["id"] = f.sessions[0].id
            friend["session"]["status"] = f.sessions[0].status
            friend["session"]["name"] = f.sessions[0].name
        response["requested"].append(friend)
    return jsonify(response)


@friends.route("/add", methods=["POST"])
@login_required
def add_friend():
    f = User.query.filter(User.name == request.form["name"]).first()
    if f == current_user:
        return "You are your friend", 400
    if not f:
        return "User not exist", 404
    if f in current_user.friends:
        return "Friend already added", 400
    if f in current_user.follows:
        return "Request already sent", 400
    current_user.f_follows.append(f)
    db.session.commit()
    friend = {"friends": f in current_user.friends, "name": f.name, "status": f.in_client,
              "session": {}}
    if f.sessions:
        friend["session"]["id"] = f.sessions[0].id
        friend["session"]["status"] = f.sessions[0].status
        friend["session"]["name"] = f.sessions[0].name
    return jsonify(friend)


@friends.route("/remove", methods=["POST"])
@login_required
def remove_friend():
    f = User.query.filter(User.name == request.form["name"]).first()
    if not f:
        return "User not exist", 404
    if f == current_user:
        return "You are your friend", 400
    if f not in current_user.follows and f not in current_user.friends:
        return "This user not friend and not in you follows", 404
    current_user.f_follows.remove(f)
    db.session.commit()
    return ""


def token_updater(token):
    session['oauth2_token'] = token


def make_session(token=None, state=None, scope=None):
    return OAuth2Session(
        client_id=app.config["OAUTH2_CLIENT_ID"],
        token=token,
        state=state,
        scope=scope,
        redirect_uri=app.config["OAUTH2_REDIRECT_URI"],
        auto_refresh_kwargs={
            'client_id': app.config["OAUTH2_CLIENT_ID"],
            'client_secret': app.config["OAUTH2_CLIENT_SECRET"],
        },
        auto_refresh_url=app.config["TOKEN_URL"],
        token_updater=token_updater)


f_discord = Blueprint("discord", __name__, template_folder="templates")

app/users/templates/users/login.html
{% extends "base.html" %}

{% block content %}
    <h1>Авторизация</h1>
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <p>
            {{ form.email.label }}<br>
            {{ form.email(class="form-control", type="email") }}<br>
            {% for error in form.email.errors %}
                <div class="alert alert-danger" role="alert">
                    {{ error }}
                </div>
            {% endfor %}
        </p>
        <p>
            {{ form.password.label }}<br>
            {{ form.password(class="form-control", type="password") }}<br>
            {% for error in form.password.errors %}
                <div class="alert alert-danger" role="alert">
                    {{ error }}
                </div>
            {% endfor %}
        </p>
        <p>{{ form.remember_me() }} {{ form.remember_me.label }}</p>
        <p>{{ form.submit(type="submit", class="btn btn-primary") }}</p>
        <div>{{ message }}</div>
    </form>
{% endblock %}

app/users/templates/users/profile.html
{% extends "base.html" %}
{% set is_current = (current_user.name == user.name) %}

{% block content %}
<h1>Профиль</h1>
<div class="container">
    <div class="row">
        <div class="col">
            <h2>{{ user.name }}</h2>
            {% if not is_current %}
            <div class="row">
                <button class="btn m-auto friend-btn
                 {% if user in current_user.friends or user in current_user.follows%}
                 remove-friend
                 {% else %}add-friend {% endif %}">
                    {% if user in current_user.friends %}Удалить из друзей
                    {% elif user in current_user.follows %}Отписаться{% else %} Добавить в друзья {%
                    endif %}
                </button>
            </div>
            {% endif %}
            <div class="row">
                <div class="col-6 d-flex m-auto justify-content-around align-items-center">
                {% if discord_user %}
                    <div class="row d-flex align-items-center">
                        <img src="{{url_for('static', filename='img/discord.png')}}" style="width: auto; height: 30px;">
                    <a href="https://discordapp.com/users/{{discord_user['id']}}">{{discord_user["username"]}}#{{discord_user["discriminator"]}}</a>
                        </div>
                    {% if is_current and 0 %}
                    <button class="btn bg-danger disconnect-discord">X</button>
                    {% endif %}
                {% elif is_current %}
                    <button class="btn connect-discord">Подключить дискорд</button>
                {% endif %}
                    </div>
            </div>
        </div>
        <div class="col">
            <table class="table">
                <thead class="thead-dark table-bordered">
                <tr>
                    <th scope="col">Общее кол-во матчей</th>
                    <th scope="col">Кол-во побед</th>
                    <th scope="col">Кол-во поражений</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>{{user.sessions_c}} {% if not is_current %}
                        {% if user.sessions_c == current_user.sessions_c %}
                        =
                        {% elif user.sessions_c > current_user.sessions_c %}
                        ▲
                        {% else %}
                        ▼
                        {%endif%}
                        {%endif%}
                    </td>
                    <td>{{user.win_sessions_c}} {% if not is_current %}
                        {% if user.win_sessions_c == current_user.win_sessions_c %}
                        =
                        {% elif user.win_sessions_c > current_user.win_sessions_c %}
                        ▲
                        {% else %}
                        ▼
                        {%endif%}
                        {%endif%}
                    </td>
                    <td>{{user.loose_sessions_c}} {% if not is_current %}
                        {% if user.loose_sessions_c == current_user.loose_sessions_c %}
                        =
                        {% elif user.loose_sessions_c > current_user.loose_sessions_c %}
                        ▲
                        {% else %}
                        ▼
                        {%endif%}
                        {%endif%}
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <table class="table">
                <thead class="thead-dark table-bordered">
                <tr>
                    <th scope="col">Номер матча</th>
                    <th scope="col">Победитель</th>
                    <th scope="col">Участники</th>
                </tr>
                </thead>
                <tbody>
                {% for session in sessions.items %}
                <tr>
                    <td scope="row">{{ loop.index + (sessions.page - 1) * 10}}</td>
                    <td>
                        <a href="{% if session.winner == current_user %}/profile{% else %}/profile/{{session.winner.name}}{% endif %}">{{session.winner.name}}</a>
                    </td>
                    <td>
                        <ul>
                            {% for suser in session.users %}
                            <li>
                                <a href="{% if suser == current_user %}
                                 /profile
                                 {% else %}/profile/{{suser.name}}{% endif %}">{{suser.name}}</a>
                            </li>
                            {% endfor %}
                        </ul>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
            <nav aria-label="User sessions navigation">
                <ul class="pagination justify-content-center">
                    <li class="page-item {%if not sessions.has_prev %}disabled{% endif %}">
                        <a class="page-link" href="?page={{sessions.prev_num}}" tabindex="-1"
                           aria-disabled="true">Предыдущая</a>
                    </li>
                    {% for page in sessions.iter_pages() %}
                    <li class="page-item"><a
                            class="page-link {% if page == sessions.page %} active {% endif %}"
                            href="?page={{page}}">{{page}}</a></li>
                    {% endfor %}
                    <li class="page-item {%if not sessions.has_next %}disabled{% endif %}">
                        <a class="page-link"
                           href="?page={{sessions.next_num}}">Следующая</a>
                    </li>
                </ul>
            </nav>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script>
    {% if not is_current %}
    $(".friend-btn").click(function () {
        let element = $(this);
        if (element.hasClass("add-friend")) {
            element.html(`<img src='{{ url_for('static', filename='img/loading.gif') }}' style='width: auto; height: ${element.height()}px'>`);
            element.toggleClass("add-friend");
            $.post('/friends/add', {
                name: "{{ user.name }}"
            }).done(function (response) {
                element.text(response["friends"] ? "Удалить из друзей" : "Отписаться");
                element.toggleClass("remove-friend");
            }).fail(function () {
                element.text("Добавить в друзья");
                element.toggleClass("add-friend");
            });
        } else if(element.hasClass("remove-friend")) {
            element.html(`<img src='{{ url_for('static', filename='img/loading.gif') }}' style='width: auto; height: ${element.height()}px'>`);
            element.toggleClass("remove-friend");
            $.post('/friends/remove', {
                name: "{{ user.name }}"
            }).done(function (response) {
                element.text("Добавить в друзья");
                element.toggleClass("add-friend");
            }).fail(function (response) {
                element.toggleClass("remove-friend");
                element.text("{% if user in current_user.friends %}Удалить из друзей{% else %}Отписаться{% endif %}");
            });
        }
    });
    {% else %}
    $(".connect-discord").click(function () {
        $(location).attr("href", "/discord/login");
    });
    $(".disconnect-discord").click(function () {
        $(location).attr("href", "/discord/revoke");
    });
    {% endif %}
</script>
{% endblock %}

app/users/templates/users/registration.html
{% extends "base.html" %}

{% block content %}
    <h1>Регистрация</h1>
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <p>
            {{ form.name.label }}<br>
            {{ form.name(class="form-control") }}<br>
            {% for error in form.name.errors %}
                <div class="alert alert-danger" role="alert">
                    {{ error }}
                </div>
            {% endfor %}
        </p>
        <p>
            {{ form.email.label }}<br>
            {{ form.email(class="form-control", type="email") }}<br>
            {% for error in form.email.errors %}
                <div class="alert alert-danger" role="alert">
                    {{ error }}
                </div>
            {% endfor %}
        </p>
        <p>
            {{ form.password.label }}<br>
            {{ form.password(class="form-control", type="password") }}<br>
            {% for error in form.password.errors %}
                <div class="alert alert-danger" role="alert">
                    {{ error }}
                </div>
            {% endfor %}
        </p>
        <p>
            {{ form.password2.label }}<br>
            {{ form.password2(class="form-control", type="password") }}<br>
            {% for error in form.password2.errors %}
                <div class="alert alert-danger" role="alert">
                    {{ error }}
                </div>
            {% endfor %}
        </p>
        <p>{{ form.submit(type="submit", class="btn btn-primary") }}</p>
        <div>{{ message }}</div>
    </form>
{% endblock %}

app/users/templates/users/unconfirmed.html
{% extends "base.html" %}

{% block content %}

<h1>Здравствуйте!</h1>
<br>
<p>Вы не подтвердили свой аккаунт. Пожалуйста, проверьте ваш почтовый ящик (и папку "Спам") - вы должны были получить письмо с подтверждением.</p>
<p>Не получили письмо? <a href="{{ url_for('users.resend_confirmation') }}">Мы пришлем его повторно</a>.</p>

{% endblock %}