app/posts/blueprint.py
from flask import Blueprint, render_template, url_for, request
from flask_breadcrumbs import register_breadcrumb

from app.models import Post, Tag

posts = Blueprint("posts", __name__, template_folder="templates")


@posts.errorhandler(404)
def error404(e):
    return render_template("posts/404.html"), 404


@posts.route("/")
@register_breadcrumb(posts, '.', 'Блог')
def index():
    page = request.args.get("page")
    if page and page.isdigit():
        page = int(page)
    else:
        page = 1
    posts = Post.query.order_by(Post.date.desc()).paginate(page=page, per_page=10)
    return render_template("posts/index.html", posts=posts)


def post_detail_breadcrumbs(*args, **kwargs):
    slug = request.view_args['slug']
    post = Post.query.filter(Post.slug == slug).first()
    if not post:
        return [{'text': "Ошибка", 'url': ""}]
    return [{'text': post.title, 'url': url_for("posts.post_detail", slug=post.slug)}]


@posts.route("/<slug>")
@register_breadcrumb(posts, '.post-slug', '', dynamic_list_constructor=post_detail_breadcrumbs)
def post_detail(slug):
    post = Post.query.filter(Post.slug == slug).first_or_404()
    return render_template("posts/post_detail.html", post=post, tags=post.tags.all())


def tag_detail_breadcrumbs(*args, **kwargs):
    slug = request.view_args['slug']
    tag = Tag.query.filter(Tag.slug == slug).first()
    if not tag:
        return [{'text': "Ошибка", 'url': ""}]
    return [{'text': 'Тег', 'url': ""},
            {'text': tag.name, 'url': url_for("posts.tag_detail", slug=tag.slug)}]


@posts.route("/tag/<slug>")
@posts.route("/tag/<slug>/")
@register_breadcrumb(posts, '.tag-slug', '', dynamic_list_constructor=tag_detail_breadcrumbs)
def tag_detail(slug):
    page = request.args.get("page")
    if page and page.isdigit():
        page = int(page)
    else:
        page = 1
    tag = Tag.query.filter(Tag.slug == slug).first_or_404()
    posts = tag.posts.order_by(Post.date.desc()).paginate(page=page, per_page=10)
    return render_template("posts/tag_detail.html", posts=posts, tag=tag)

# @posts.route("/create", methods=["POST", "GET"])
# @login_required
# def create_post():
#     form = PostForm()
#     if form.validate_on_submit():
#         try:
#             post = Post(title=form.title, description=form.description, author_id=current_user.id)
#             if form.file:
#                 filename = secure_filename(form.file.filename)
#                 path = os.path.join(app.config['UPLOAD_FOLDER'], filename)
#                 form.file.save(path)
#                 post.img = path
#                 db.session.add(post)
#                 db.session.commit()
#         except Exception as e:
#             print(e)
#
#     return render_template("posts/create_post.html", form=form)

app/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
          crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/sticky-footer-navbar/">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"></script>
    <script type="text/javascript"
            src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js">
    </script>
    <title>{{title}} | BestGameInMyMind</title>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
        <a class="navbar-brand" href="{{url_for('home')}}">BestGameInMyMind</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse"
                data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <nav class="navbar navbar-light bg-light">
                <form id="search" class="form-inline" method="GET" action="/search">
                    <input id="query-field" class="form-control mr-sm-2" type="search"
                           placeholder="Поиск" aria-label="Search" name="q"
                           value="{{request.args.get('q', '')}}">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Поиск
                    </button>
                </form>
            </nav>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item"><a class="nav-link"
                                        href="{{ url_for('posts.index') }}">Блог</a></li>
                <li class="nav-item"><a class="nav-link" href="{{ url_for('rating') }}">Рейтинг</a>
                </li>
                {% if current_user.is_active %}
                {% if current_user.confirmed and current_user.is_authenticated %}
                <li class="nav-item"><a class="nav-link" href="{{ url_for('users.profile') }}">Профиль</a>
                </li>
                {% elif current_user.is_authenticated %}
                <li class="nav-item"><a class="nav-link" href="{{ url_for('users.unconfirmed') }}">Подтвердить</a>
                </li>
                {% endif %}
                <li class="nav-item"><a class="nav-link" href="/logout">Выход</a></li>
                {% else %}
                <li class="nav-item"><a class="nav-link" href="/login">Вход</a></li>
                <li class="nav-item"><a class="nav-link" href="/registration">Регистрация</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
</header>
<!-- Begin page content -->
<nav aria-label="breadcrumb" class="breadcrumb-nav">
    <ol class="breadcrumb">
        {% for breadcrumb in breadcrumbs %}
        <li class="breadcrumb-item"><a {% if not breadcrumb.url or breadcrumb.url=='#' %}
                                       class="disabled" {% else %} href="{{ breadcrumb.url }}" {%
                                       endif %}>{{ breadcrumb.text }}</a></li>
        {% endfor %}
    </ol>
</nav>
<main role="main" class="container col-6 pt-5 content">
    {% block content %}{% endblock %}
</main>
<footer class="bg-dark p-3 text-white footer">
    <div class="row justify-content-between">
        <div class="col-3">
            <div class="row justify-content-center">
                <span>Сайт создан в 2020 by IsqK</span>
            </div>
        </div>
        <div class="col-3">
            <div class="row">
                <div class="col">
                    <div class="row justify-content-center">
                        <a class="btn btn-danger" href="mailto:plabolchar23@gmail.com">Обратная
                            связь</a>
                    </div>
                </div>
                <div class="col">
                    <a href="https://discord.gg/y2jsYhf" target="_blank" class="btn btn-info">Discord</a>
                </div>
            </div>
        </div>
    </div>
</footer>
{% block scripts %}{% endblock %}
</body>
</html>